import Head from "next/head";

interface Props {}

const about = (props: Props) => {
  return (
    <div>
      <Head>
        <title>Music Party App - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>About</h1>
    </div>
  );
};

export default about;
