import Head from "next/head";
import styles from "../styles/Home.module.css";

interface Props {}

export default function Home(props: Props) {
  return (
    <div>
      <Head>
        <title>Music Party App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Index</h1>

    </div>
  );
}
